### ISSUE TITLE
Doesn't Reduce any space/memory consumption.

### ISSUE THREAD

**Issue by shivam05011996** [agnusmaximus/Word2Bits#7]
Hi @agnusmaximus @loretoparisi 
The description provides that it will reduce the space consumption by 8x to 16x times. But I dont see any much reduction in the space/memory consumption when compared to original word2vec.

I ran it on text8 corpus and here are my results - 
**Word2vec**
Command - time ./word2vec -train text8 -output vectors.bin -cbow 1 -size 300 -window 10 -negative 20 -hs 0 -sample 1e-6 -threads 20 -binary 1 -iter 15

Vocab Size - 71291
Ram - VIRT= 2134, RES=685, SHR=2168
Time - 4m27s
output file size - 83M

**Word2bits**
Command - time ./word2bits -train ../word2vec/text8 -bitlevel 1 -size 300 -window 10 -negative 20 -threads 20 -iter 15  -output 1bit_300d_vectors -binary 1 -sample 1e-6

Vocab Size - 71291
Ram - VIRT= 2134, RES=683, SHR=3306
Time - 8m34s
output file size - 83M

Is there some kind of switch which turn on low space consumption or some thing is very badly wrong.
Any comment is appreciated.

**Comment by agnusmaximus** [comment]
Hey Shivam, there is no space saving during training the word vectors -- space can only be saved at application time when the vectors are used since the values are constrained +/-1 (however you'd need to write custom code to encode/decode these quantized vectors to see the space savings). I should have been more clear about this in the  arxiv writeup, sorry about the misunderstanding!
